#ifndef PU_FAULT_CODE_H
#define PU_FAULT_CODE_H

/*
 * Fault codes use the 0xSSSSFFFF format, where S identifies the
 * subsystem and F identifies the specific fault. The subsystem
 * occupies the upper 16 bits and the fault occupies the lower
 * 16 bits. Fault codes are generated by adding the fault offset
 * to the subsystem base.
 */

/* Task fault codes */
#define TASK_FAULT_BASE (0x01U << 16)

#define PU_TASK_OK (TASK_FAULT_BASE + 0x01U)
#define PU_TASK_NULL_FUNCTION (TASK_FAULT_BASE + 0x02U)
#define PU_TASK_STACK_TOO_SMALL (TASK_FAULT_BASE + 0x03U)
#define PU_TASK_STACK_TOO_BIG (TASK_FAULT_BASE + 0x04U)
#define PU_TASK_MEMORY_ALLOCATION_FAILED (TASK_FAULT_BASE + 0x05U)
#define PU_TASK_CONTEXT_CREATION_FAILED (TASK_FAULT_BASE + 0x06U)

/* Kernel interface fault codes */
#define KERNEL_INTERFACE_FAULT_BASE (0x02U << 16)

#define PU_KERNEL_INTERFACE_CONTEXT_CREATE_INVALID (KERNEL_INTERFACE_FAULT_BASE + 0x01U)
#define PU_KERNEL_INTERFACE_CONTEXT_RESTORE_INVALID (KERNEL_INTERFACE_FAULT_BASE + 0x02U)
#define PU_KERNEL_INTERFACE_CONTEXT_SAVE_INVALID (KERNEL_INTERFACE_FAULT_BASE + 0x03U)

/* Allocator fault codes */
#define ALLOCATOR_FAULT_BASE (0x03U << 16)

#define PU_ALLOCATOR_NOT_ENOUGH_SPACE (ALLOCATOR_FAULT_BASE + 0x01U)

#endif /* PU_FAULT_CODE_H */
