#ifndef PU_FAULT_CODE_H
#define PU_FAULT_CODE_H

#define TASK_FAULT_BASE (0x01U << 16)

#define PU_TASK_OK (TASK_FAULT_BASE + 0x01U)
#define PU_TASK_NULL_FUNCTION (TASK_FAULT_BASE + 0x02U)
#define PU_TASK_STACK_TOO_SMALL (TASK_FAULT_BASE + 0x03U)
#define PU_TASK_STACK_TOO_BIG (TASK_FAULT_BASE + 0x04U)
#define PU_TASK_MEMORY_ALLOCATION_FAILED (TASK_FAULT_BASE + 0x05U)
#define PU_TASK_CONTEXT_CREATION_FAILED (TASK_FAULT_BASE + 0x06U)

#endif /* PU_FAULT_CODE_H */
